fix: disconnect on PoW peer message
scroll-tech/reth pull request #119
Opened 2024-12-27 20:26 UTC by greged93

Avoid disconnecting peer on `NewBlock` and `NewBlockHashes` peer messages. Feature flag the disconnect and simply log the block hash(es) when "scroll" feature is active.

2024-12-30 13:31 UTC, frisitano requested changes
I don't think the `scroll` feature flag is suitable here as it has implications for the state commitment types/operations. For example, the `scroll` feature flag is not compatible with the native mpt implementation. 

I wonder if instead of introducing a feature flag we should see if we can modify the `NetworkConfig` to use `PoW` instead of `PoS`? 
https://github.com/scroll-tech/reth/blob/dba97466eda4e5a03bb0ef6e0bcd273850102c83/crates/net/network/src/config.rs#L70-L71

2024-12-30 13:31 UTC, frisitano commented on crates/net/network/src/manager.rs
>                  })
Is the `scroll` feature flag suitable here? The `scroll` feature flag has implications for the state commitment logic.

2025-01-07 04:56 UTC, frisitano approved these changes
Looks good! What are the implications here? Does this mean we can sync the node via the existing L2 P2P network after this change?

2025-01-07 07:42 UTC, greged93 commented
we could sync the node via the L2 P2P before this change, but we were getting a lot of disconnects due to the `NewBlock` and `NewBlockHashes` messages. With this fix, we don't get disconnected anymore.

2025-01-07 12:53 UTC, merged